import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="generator" content="Mobirise AI v0.01, ai.mobirise.com" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1"
        />
        <link
          rel="shortcut icon"
          href="assets/images/logo5.png"
          type="image/x-icon"
        />
        <meta
          name="description"
          content="The health and wellness blog is a comprehensive platform dedicated to providing expert articles, tips, and resources to promote holistic well-being."
        />
        <title>Empower Your Health</title>
        <link
          rel="stylesheet"
          href="assets/web/assets/mobirise-icons2/mobirise2.css"
        />
        <link rel="stylesheet" href="/assets/parallax/jarallax.css" />
        <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css" />
        <link
          rel="stylesheet"
          href="/assets/bootstrap/css/bootstrap-grid.min.css"
        />
        <link
          rel="stylesheet"
          href="/assets/bootstrap/css/bootstrap-reboot.min.css"
        />
        <link rel="stylesheet" href="/assets/dropdown/css/style.css" />
        <link rel="stylesheet" href="/assets/socicon/css/styles.css" />
        <link rel="stylesheet" href="/assets/animatecss/animate.css" />
        <link rel="stylesheet" href="/assets/theme/css/style.css" />
        <link
          rel="preload"
          href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap"
          as="style"
        />
        <noscript>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&amp;display=swap"
          />
        </noscript>
        <link
          rel="preload"
          as="style"
          href="assets/mobirise/css/additional.css"
        />
      </Head>
      <body className={inter.className}>
        {children}
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
          defer
        ></script>
        <script src="/assets/parallax/jarallax.js" defer></script>
        <script src="/assets/dropdown/js/navbar-dropdown.js" defer></script>
        <script src="/assets/scrollgallery/scroll-gallery.js" defer></script>
        <script src="/assets/mbr-switch-arrow/mbr-switch-arrow.js" defer></script>
        <script src="/assets/smoothscroll/smooth-scroll.js" defer></script>
        <script src="/assets/ytplayer/index.js" defer></script>
        <script src="/assets/theme/js/script.js" defer></script>
        <script src="/assets/formoid/formoid.min.js" defer></script>
      </body>
    </>
  );
};

export default RootLayout;
